[versions]
buildconfig = "6.0.7"
compose = "1.10.2"
coroutines = "1.10.2"
detekt = "2.0.0-alpha.2"
kotlin = "2.4.0"
webpack = "5.104.1"
webpackCli = "6.0.1"
webpackDevServer = "5.2.3"

[libraries]
compose-html = { module = "org.jetbrains.compose.html:html-core", version.ref = "compose" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
coroutines-core-js = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version.ref = "coroutines" }
detekt-ktlintWrapper = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt" }

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }