name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  detekt:
    name: Run detekt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run detekt with ktlint
        run: ./gradlew detektJsMain

  build_project:
    name: Build KotlinJS project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: KotlinJS project
        run: ./gradlew jsBrowserDistribution