name: Deploy

on:
  push:
    tags:
      - '**'

jobs:
  build-and-deploy:
    name: Build and deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build webpack production bundle
        run: ./gradlew jsBrowserDistribution
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/dist/js/productionExecutable # The folder the action should deploy.