name: Deploy

on:
  push:
    tags:
      - '**'

jobs:
  build-and-deploy:
    name: Build and deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'zulu'
          java-version: '25'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5
      - name: Build webpack production bundle
        run: ./gradlew jsBrowserDistribution
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/dist/js/productionExecutable # The folder the action should deploy.