name: Deploy

on:
  push:
    tags:
      - '**'

jobs:
  build-and-deploy:
    name: Build and deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          distribution: 'zulu'
          java-version: '25'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6
      - name: Build webpack production bundle
        run: ./gradlew jsBrowserDistribution
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/dist/js/productionExecutable # The folder the action should deploy.